Lua SLAM replacement
tpan496/Horde pull request #47
Opened 2021-03-08 20:08 UTC by Ultimeit

No one asked for that, no one even bothers using SLAM's cuz it's one of the most useless weapons in Horde currently, but I did it ʕ•ᴥ•ʔ
On a bit more serious note, this replaces built-in npc_tripmine upon placement with a bit more PvE oriented counterpart.
Only owner(or NPC's) can detonate it by dealing damage, also it's getting triggered only by NPC's. Damage/Explosion radius is configurable to be further balanced. Laser length is limited, because no one needs lasers that cross whole map. It also can be defused(ConVar horde_tripmine_reusable) by owner(or by anyone if owner disconnected), if it has correct class, by pressing +use on it.
P.S.I wonder how much zombies I could've killed today instead of spending so much time on researching useless SLAM mechanics...

2021-03-08 20:12 UTC, Ultimeit commented
That reminds me, that current engineer turrets are NPC's too and guess they can detonate mines by dealing damage to it >.>

2021-03-09 05:02 UTC, tpan496 requested changes
This is some good stuff; I almost forgot SLAM exists. Have some small style comments.

2021-03-09 15:13 UTC, Ultimeit commented on entities/entities/npc_tripmine_horde/init.lua
> +local defuse = Sound("weapons/c4/c4_disarm.wav")
Afaik, missing sounds doesn't cause errors. Though this probably should be changed to some kind of HL2 sound.

2021-03-09 15:20 UTC, Ultimeit commented on entities/entities/npc_tripmine_horde/cl_init.lua
> +
I wouldn't mind if you'll replace tabs into spaces, however stopping using tabs for me would be problematic. That's pretty old habit for me already.

2021-03-09 15:21 UTC, Ultimeit commented on entities/entities/npc_tripmine_horde/init.lua
> +	-- btw, saboteur class when?
Ugh, sadly no one ported Izaro to gmod yet, guess we should delay saboteur ascendancy then.

2021-03-09 16:08 UTC, Ultimeit commented
Also, 2.4x damage of RPG(10$ per shot) hit with estimate same AoE radius doesn't sounds that impressive for a mine(100$ per mine). Guess either RPG ammo or SLAM ammo price should be rebalanced. 
Also, wouldn't mind if I'll make Incendiary grenade to use different ammo than HL2 grenades? Guess that's pretty obvious that they are way too powerful even for 100$. Also their ammo can be duped infinitely by playing demolition class and constantly dropping HL2 grenade and receiving a new one from perk, gonna post that to issues list as well as possible fix.

2021-03-09 18:02 UTC, tpan496 commented on entities/entities/npc_tripmine_horde/cl_init.lua
> +
For this PR, this is fine. However, if you are making changes to existing files you **have** to use spaces. Not sure which editor you are using, but on VS code it doesn't any effort to do that (just a simple toggle on the top right corner), and even if you are pressing tabs the editor still generates spaces.

2021-03-09 18:04 UTC, tpan496 commented
LGTM 👍

2021-03-09 18:04 UTC, merged